--
-- PostgreSQL database dump
--

\restrict T7kA3uSWabnN1U6yhDqQOrShhyBuLfsc3aKCH060cC7Sobg15rIyZ6eUNvbqnc4

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-01-15 16:27:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    data_criacao timestamp(6) without time zone,
    descricao text,
    prioridade character varying(255),
    status character varying(255),
    titulo character varying(255) NOT NULL
);


ALTER TABLE public.tickets OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16400)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    cpf character varying(255),
    nome character varying(255),
    senha character varying(255),
    tipo character varying(255)
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16399)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5013 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tickets (id, data_criacao, descricao, prioridade, status, titulo) FROM stdin;
4	2026-01-15 15:44:22.234465	O sistema conectou com sucesso!	BAIXA	FECHADO	Dúvida Resolvida
6	2026-01-15 16:11:00.340898	O sistema conectou com sucesso!	BAIXA	FECHADO	Dúvida Resolvida
7	2026-01-15 16:16:46.365681	O sistema conectou com sucesso!	BAIXA	FECHADO	Dúvida Resolvida
1	2026-01-14 18:28:45.530992	Agora os dados ficam salvos!	ALTA	EM ANDAMENTO	Teste PostgreSQL
2	2026-01-14 19:24:41.564471	O sistema conectou com sucesso!	BAIXA	ABERTO	Dúvida Resolvida
\.


--
-- TOC entry 5015 (class 0 OID 16400)
-- Dependencies: 222
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, cpf, nome, senha, tipo) FROM stdin;
1	70367528401	Bia	123	cliente
3	70367528401	Bia	123	cliente
2	70367528401	Bia	123	cliente
4	03764375450	Beatriz Regina de Figueiredo	bia	cliente
5	70367528402	Regina figueiredo	senha	tecnico
\.


--
-- TOC entry 5021 (class 0 OID 0)
-- Dependencies: 219
-- Name: tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tickets_id_seq', 7, true);


--
-- TOC entry 5022 (class 0 OID 0)
-- Dependencies: 221
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 5, true);


--
-- TOC entry 4862 (class 2606 OID 16398)
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 16407)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


-- Completed on 2026-01-15 16:27:44

--
-- PostgreSQL database dump complete
--

\unrestrict T7kA3uSWabnN1U6yhDqQOrShhyBuLfsc3aKCH060cC7Sobg15rIyZ6eUNvbqnc4

